CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS_DB.RAW;

CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS_DB.BRONZE;

CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS_DB.SILVER;

CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS_DB.GOLD;