CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_CATEGORY_NAME VARCHAR,
    PRODUCT_NAME_LENGHT NUMBER(5),
    PRODUCT_DESCRIPTION_LENGHT NUMBER(5),
    PRODUCT_PHOTOS_QTY NUMBER(5),
    PRODUCT_WEIGHT_G NUMBER(10),
    PRODUCT_LENGTH_CM NUMBER(10),
    PRODUCT_HEIGHT_CM NUMBER(10),
    PRODUCT_WIDTH_CM NUMBER(10)
);