CREATE OR REPLACE TABLE RAW.CAMPAIGNS (
    CAMPAIGN_ID VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    PLATFORM VARCHAR,
    CAMPAIGN_DATE DATE,
    SPEND NUMBER(10,2),
    CLICKS NUMBER(10),
    IMPRESSIONS NUMBER(10)
);