CREATE OR REPLACE TABLE RAW.ORDER_ITEMS (
    ORDER_ID VARCHAR,
    ORDER_ITEM_ID NUMBER(5),
    PRODUCT_ID VARCHAR,
    SELLER_ID VARCHAR,
    SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
    PRICE NUMBER(10,2),
    FREIGHT_VALUE NUMBER(10,2)
);